import {z} from 'zod';
import {db,identity,body,json,error,ApiError,getSettings,manager,employee} from '@/lib/server';
import {SERVICES,STATUSES,Order,today} from '@/lib/domain';
export const dynamic='force-dynamic';
const text=z.string().trim().min(1).max(120);
const booking=z.object({service:z.enum(['express','signature','detail']),slot:z.string().datetime({offset:true}),customer:text,phone:z.string().regex(/^\+?[\d\s()-]{10,22}$/).refine(v=>v.replace(/\D/g,'').length>=10&&v.replace(/\D/g,'').length<=15),car:text,plate:z.string().trim().min(2).max(20),consent:z.literal(true),id:z.string().uuid()}).strict();
function serviceSlots(slot:string,duration:number){return Array.from({length:duration/30},(_,i)=>new Date(new Date(slot).getTime()+i*1800000).toISOString())}
function validSlot(slot:string,duration:number){const t=new Date(slot),moscow=new Date(t.getTime()+10800000);const minutes=moscow.getUTCHours()*60+moscow.getUTCMinutes();return t.getTime()>Date.now()+300000&&t.getTime()<Date.now()+30*86400000&&t.getUTCSeconds()===0&&t.getUTCMilliseconds()===0&&minutes>=540&&minutes+duration<=1260&&minutes%30===0;}
async function getOrder(id:string){const o=await db().prepare('SELECT * FROM orders WHERE id = ?').bind(id).first<Order>();if(!o)throw new ApiError(404,'Заказ не найден.');return o;}
async function record(o:Order,actor:string,update:Record<string,unknown>,note:string){const now=new Date().toISOString();const id=crypto.randomUUID();const allowed=['status','paid','employee','intake','mileage','proposedTotal','proposalNote','total'];if(Object.keys(update).some(k=>!allowed.includes(k)))throw new Error('Invalid field');const fields=Object.keys(update);const statements=[db().prepare(`UPDATE orders SET ${fields.map(k=>k+' = ?').join(', ')}, updatedAt = ?, version = version + 1 WHERE id = ? AND version = ?`).bind(...Object.values(update),now,o.id,o.version),db().prepare('INSERT INTO events (id,orderId,actor,status,note,createdAt) SELECT ?,?,?,?,?,? WHERE changes() = 1').bind(id,o.id,actor,String(update.status||o.status),note,now)];if(update.status==='cancelled'||update.status==='delivered')statements.push(db().prepare('DELETE FROM reservations WHERE orderId = ? AND EXISTS (SELECT 1 FROM events WHERE id = ?)').bind(o.id,id));const r=await db().batch(statements);if(!r[0].meta.changes)throw new ApiError(409,'Заказ уже изменён. Обновите страницу и повторите.');}
export async function GET(req:Request){try{const url=new URL(req.url),view=url.searchParams.get('view')||'public';if(view==='public'){const settings=await getSettings();const reviews=await db().prepare('SELECT id,name,rating,body,createdAt FROM reviews WHERE approved = 1 ORDER BY createdAt DESC LIMIT 12').all();return json({settings,reviews:reviews.results});}
if(view==='availability'){const day=url.searchParams.get('day')||today();if(!/^\d{4}-\d{2}-\d{2}$/.test(day))throw new ApiError(400,'Неверная дата.');const s=SERVICES.find(s=>s.id===url.searchParams.get('service'))||SERVICES[1];const occupied=(await db().prepare('SELECT slot,bay FROM reservations WHERE slot >= ? AND slot < ?').bind(new Date(day+'T00:00:00+03:00').toISOString(),new Date(day+'T23:59:59+03:00').toISOString()).all<{slot:string;bay:number}>()).results;const slots=[];for(let m=540;m+s.duration<=1260;m+=30){const slot=new Date(`${day}T${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}:00+03:00`).toISOString();if(!validSlot(slot,s.duration))continue;const parts=serviceSlots(slot,s.duration);const available=[1,2].some(b=>!occupied.some(r=>r.bay===b&&parts.includes(r.slot)));slots.push({slot,available});}return json({slots});}
const u=await identity();if(view==='me')return json({user:{name:u.displayName,email:u.email,role:u.role}});
if(view==='staff'){manager(u.role);return json({staff:(await db().prepare('SELECT * FROM staff ORDER BY name').all()).results});}
if(view==='reviews'){manager(u.role);return json({reviews:(await db().prepare('SELECT * FROM reviews ORDER BY createdAt DESC LIMIT 100').all()).results});}
if(view==='orders'){const all=url.searchParams.get('all')==='1';if(all)employee(u.role);const orders=(await db().prepare(all?'SELECT * FROM orders ORDER BY slot DESC LIMIT 300':'SELECT * FROM orders WHERE userId = ? ORDER BY slot DESC LIMIT 100').bind(...(all?[]:[u.userId])).all<Order>()).results;return json({orders,user:{name:u.displayName,email:u.email,role:u.role}});}
if(view==='order'){const o=await getOrder(url.searchParams.get('id')||'');if(o.userId!==u.userId)employee(u.role);const events=(await db().prepare('SELECT id,status,note,createdAt FROM events WHERE orderId = ? ORDER BY createdAt,id').bind(o.id).all()).results;const reviewed=!!await db().prepare('SELECT id FROM reviews WHERE orderId = ?').bind(o.id).first();return json({order:{...o,events,reviewed},user:{name:u.displayName,email:u.email,role:u.role}});}throw new ApiError(404,'Не найдено.');}catch(e){return error(e)}}
export async function POST(req:Request){try{const u=await identity(),b=await body(req);const action=b.action;
if(action==='book'){const parsed=booking.safeParse(b.data);if(!parsed.success)throw new ApiError(400,'Проверьте имя, телефон, автомобиль и согласие.');const d=parsed.data;const existing=await db().prepare('SELECT id,userId FROM orders WHERE id = ?').bind(d.id).first<{id:string;userId:string}>();if(existing){if(existing.userId!==u.userId)throw new ApiError(409,'Повторите запись.');return json({id:existing.id});}const s=SERVICES.find(s=>s.id===d.service)!;if(!validSlot(d.slot,s.duration))throw new ApiError(400,'Выберите свободное время в ближайшие 30 дней.');const active=await db().prepare("SELECT count(*) AS n FROM orders WHERE userId = ? AND status NOT IN ('delivered','cancelled')").bind(u.userId).first<{n:number}>();if((active?.n||0)>=5)throw new ApiError(429,'У вас уже пять активных записей.');const settings=await getSettings(),total=settings.prices[SERVICES.findIndex(x=>x.id===s.id)],slot=new Date(d.slot).toISOString(),now=new Date().toISOString();for(const bay of [1,2]){try{await db().batch([db().prepare('INSERT INTO orders (id,userId,customer,phone,car,plate,service,slot,bay,status,total,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(d.id,u.userId,d.customer,d.phone,d.car,d.plate.toUpperCase(),d.service,slot,bay,'booked',total,now,now),...serviceSlots(slot,s.duration).map(t=>db().prepare('INSERT INTO reservations (id,orderId,slot,bay) VALUES (?,?,?,?)').bind(crypto.randomUUID(),d.id,t,bay)),db().prepare('INSERT INTO events (id,orderId,actor,status,note,createdAt) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),d.id,u.userId,'booked','Запись подтверждена. Клиент согласился на обработку данных для выполнения заказа и с условиями услуги v1.',now)]);return json({id:d.id},201);}catch(e){if(!String(e).includes('UNIQUE'))throw e;}}throw new ApiError(409,'Это время только что заняли. Выберите другое.');}
if(action==='settings'){manager(u.role);const v=z.object({address:z.string().trim().max(250),city:z.string().trim().max(100),phone:z.string().max(30).refine(v=>!v||/^\+?[\d\s()-]{10,22}$/.test(v)),whatsapp:z.string().max(300),telegram:z.string().max(300),instagram:z.string().max(300),tiktok:z.string().max(300),latitude:z.string().max(30).refine(v=>!v||(Number.isFinite(Number(v))&&Math.abs(Number(v))<=90)),longitude:z.string().max(30).refine(v=>!v||(Number.isFinite(Number(v))&&Math.abs(Number(v))<=180)),legalName:z.string().trim().max(200),legalInfo:z.string().trim().max(1500),prices:z.array(z.number().int().min(100).max(100000)).length(3)}).strict().safeParse(b.data);if(!v.success)throw new ApiError(400,'Проверьте контакты, координаты и цены.');for(const key of ['whatsapp','telegram','instagram','tiktok'] as const){const value=v.data[key];if(!value)continue;const hosts={whatsapp:['wa.me','api.whatsapp.com'],telegram:['t.me'],instagram:['instagram.com','www.instagram.com'],tiktok:['tiktok.com','www.tiktok.com']};let url;try{url=new URL(value)}catch{throw new ApiError(400,'Ссылки должны начинаться с https://');}if(url.protocol!=='https:'||!hosts[key].includes(url.hostname)||url.username||url.password)throw new ApiError(400,'Используйте официальную ссылку '+key);}await db().prepare('INSERT INTO settings (id,value) VALUES (1,?) ON CONFLICT(id) DO UPDATE SET value = excluded.value').bind(JSON.stringify(v.data)).run();return json({ok:true});}
if(action==='staff'){if(u.role!=='owner')throw new ApiError(403,'Состав команды меняет владелец.');const v=z.object({email:z.string().trim().email().max(200),name:text,role:z.enum(['manager','employee','remove'])}).safeParse(b.data);if(!v.success)throw new ApiError(400,'Проверьте email и роль.');const d=v.data;if(d.email.toLowerCase()===u.email.toLowerCase())throw new ApiError(400,'Роль владельца изменить нельзя.');if(d.role==='remove')await db().prepare('DELETE FROM staff WHERE email = ?').bind(d.email.toLowerCase()).run();else await db().prepare('INSERT INTO staff (email,name,role) VALUES (?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role').bind(d.email.toLowerCase(),d.name,d.role).run();return json({ok:true});}
if(action==='moderate'){manager(u.role);const d=z.object({id:z.string().uuid(),approved:z.boolean()}).parse(b.data);await db().prepare('UPDATE reviews SET approved = ? WHERE id = ?').bind(d.approved?1:0,d.id).run();return json({ok:true});}
const id=z.string().uuid().safeParse(b.id);if(!id.success)throw new ApiError(400,'Неверный заказ.');const o=await getOrder(id.data);
if(['cancel','approve_price','review'].includes(action)){if(o.userId!==u.userId)throw new ApiError(403,'Это не ваш заказ.');if(action==='cancel'){if(o.status!=='booked')throw new ApiError(409,'Автомобиль уже принят. Свяжитесь с сотрудником.');await record(o,u.userId,{status:'cancelled'},'Клиент отменил запись.');}
if(action==='approve_price'){if(o.proposedTotal===null||!['accepted','washing','quality'].includes(o.status))throw new ApiError(409,'Нет доплаты для согласования.');await record(o,u.userId,{total:o.proposedTotal,proposedTotal:null,proposalNote:null},'Клиент согласовал новую стоимость: '+o.proposedTotal+' ₽. '+(o.proposalNote||''));}
if(action==='review'){if(o.status!=='delivered')throw new ApiError(409,'Отзыв доступен после выдачи автомобиля.');const d=z.object({rating:z.number().int().min(1).max(5),body:z.string().trim().min(10).max(1500)}).safeParse(b.data);if(!d.success)throw new ApiError(400,'Оцените услугу и напишите от 10 до 1500 символов.');try{await db().prepare('INSERT INTO reviews (id,orderId,userId,name,rating,body,createdAt) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),o.id,u.userId,o.customer.split(' ')[0],d.data.rating,d.data.body,new Date().toISOString()).run();}catch(e){if(String(e).includes('UNIQUE'))throw new ApiError(409,'Вы уже оставили отзыв.');throw e;}}return json({ok:true});}
employee(u.role);if(action==='status'){const next=z.enum(['accepted','washing','quality','ready','delivered','cancelled']).parse(b.status);if(next==='cancelled'){manager(u.role);if(o.status!=='booked')throw new ApiError(409,'Отмена доступна до приёмки.');}else if(STATUSES.indexOf(next)!==STATUSES.indexOf(o.status as typeof STATUSES[number])+1)throw new ApiError(409,'Этапы проходят последовательно.');if(next==='delivered'&&!o.paid)throw new ApiError(409,'Сначала подтвердите оплату.');if(next==='ready'&&o.proposedTotal!==null)throw new ApiError(409,'Дождитесь согласования стоимости клиентом.');let update:Record<string,unknown>={status:next};if(next==='accepted'){const d=z.object({intake:z.string().trim().min(3).max(1000),mileage:z.string().trim().regex(/^\d{1,7}$/)}).safeParse(b.data);if(!d.success)throw new ApiError(400,'Укажите пробег и состояние при приёмке.');update={...update,intake:d.data.intake,mileage:d.data.mileage,employee:u.fullName||u.email};}await record(o,u.userId,update,next==='accepted'?'Автомобиль принят. '+String(update.intake):'Этап обновлён сотрудником.');return json({ok:true});}
if(action==='paid'){if(o.status!=='ready'||o.paid)throw new ApiError(409,'Оплата отмечается один раз, когда машина готова.');await record(o,u.userId,{paid:1},'Сотрудник подтвердил получение оплаты: '+o.total+' ₽.');return json({ok:true});}
if(action==='propose'){manager(u.role);if(!['accepted','washing','quality'].includes(o.status)||o.proposedTotal!==null)throw new ApiError(409,'Сейчас изменить стоимость нельзя.');const d=z.object({total:z.number().int().min(100).max(100000),note:z.string().trim().min(5).max(500)}).parse(b.data);await record(o,u.userId,{proposedTotal:d.total,proposalNote:d.note},'Стоимость '+d.total+' ₽ отправлена клиенту на согласование. '+d.note);return json({ok:true});}throw new ApiError(400,'Неизвестное действие.');}catch(e){if(e instanceof z.ZodError)return json({error:'Проверьте введённые данные.'},400);return error(e)}}
